name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup JDK 11"
        id: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF:10}
          echo ::set-output name=version::${GITHUB_REF:11}
      - name: "Copy secrets"
        run: |
          echo "VERSION_NAME=${{ steps.vars.outputs.version }}" >> gradle.properties
      - name: "./gradlew assemble"
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        with:
          arguments: assemble
      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: "Upload .aar"
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: library/build/outputs/aar/library-release.aar
          asset_name: bindin-${{ steps.vars.outputs.tag }}.aar
          asset_content_type: application/zip
